// Vanilla facts as derived data (never vanilla pixels): every creature id
// with its castes and flags, every tile page id, every graphics raw file
// name, and every token used inside a creature graphics block. Lets the
// validator run on any machine without a DF install.
// Usage: node tools/vanilla-index.ts [--df <path>] [--out data/vanilla-index.json]
import { basename, dirname, join } from 'node:path';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { RawDocument, readCreatures } from '../src/engine/index.ts';
import type { VanillaIndex } from '../src/engine/index.ts';
import { dfDir } from './df-dir.ts';

const argv = process.argv.slice(2);
const vanilla = join(dfDir(argv), 'data', 'vanilla');
const oi = argv.indexOf('--out');
const out = oi >= 0 ? argv[oi + 1] : join('data', 'vanilla-index.json');

const files = (readdirSync(vanilla, { recursive: true }) as string[])
  .filter(f => f.endsWith('.txt')).map(f => join(vanilla, f)).sort();

const creatures = new Map<string, { castes: Set<string>; flags: Set<string> }>();
const tilePageIds = new Set<string>();
const graphicsFiles = new Set<string>();
const tokens = new Set<string>();

for (const path of files) {
  const doc = RawDocument.fromBytes(new Uint8Array(readFileSync(path)));
  const type = doc.objectType();
  if (type === 'CREATURE') {
    for (const def of readCreatures(doc)) {
      const c = creatures.get(def.id) ?? { castes: new Set(), flags: new Set() };
      def.castes.forEach(x => c.castes.add(x));
      def.flags.forEach(x => c.flags.add(x));
      creatures.set(def.id, c);
    }
  } else if (type === 'GRAPHICS' || type === 'TILE_PAGE') {
    // Vanilla splits tile pages into their own OBJECT:TILE_PAGE files
    // (tile_page_creatures.txt) separate from the OBJECT:GRAPHICS files that
    // reference them by id.
    graphicsFiles.add(basename(path));
    for (const tp of doc.tilePages()) tilePageIds.add(tp.id);
    if (type === 'GRAPHICS') for (const cg of doc.creatureGraphics()) for (const e of cg.entries) tokens.add(e.args[0]);
  }
}

const result: VanillaIndex & { note: string } = {
  note: 'Generated by tools/vanilla-index.ts.',
  creatures: Object.fromEntries([...creatures].sort(([a], [b]) => a.localeCompare(b))
    .map(([id, c]) => [id, { castes: [...c.castes].sort(), flags: [...c.flags].sort() }])),
  tilePageIds: [...tilePageIds].sort(),
  graphicsFiles: [...graphicsFiles].sort(),
  tokens: [...tokens].sort(),
};
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(result, null, 1) + '\n');
console.log(`${creatures.size} creatures, ${tilePageIds.size} tile pages, ${graphicsFiles.size} graphics files, ${tokens.size} tokens`);
console.log(`written to ${out}`);
